import Todo from "@/components/Todo";
import Head from "next/head";
import { useEffect, useState } from "react";

const API_BASE = "http://localhost:3002";

interface TodoType {
  _id: string;
  text: string;
  complete: boolean;
  timestamp: string;
}

export default function Home() {
  const [todos, setTodos] = useState<TodoType[] | []>([]);
  const [popupActive, setPopupActive] = useState(false);
  const [newTodo, setNewTodo] = useState("");

  const GetTodos = () => {
    fetch(API_BASE + "/todos")
      .then((res) => res.json())
      .then((data) => setTodos(data))
      .catch((error) => console.error("Error: ", error));
  };

  useEffect(() => {
    GetTodos();
  }, []);

  const completeToDo = async (id: string) => {
    const data: TodoType = await fetch(API_BASE + "/todo/complete/" + id, {
      method: "PUT",
    }).then((res) => res.json());

    setTodos((todos) =>
      todos.map((todo) => {
        if (todo._id === data._id) {
          todo.complete = data.complete;
        }
        return todo;
      })
    );
  };

  const deleteTodo = async (id: string) => {
    const data: TodoType = await fetch(API_BASE + "/todo/delete/" + id, {
      method: "DELETE",
    }).then((res) => res.json());

    setTodos((todos) => todos.filter((todo) => todo._id !== data._id));
  };

  return (
    <div className="bg-darkAlt text-light min-h-screen p-16">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl font-bold mb-5">Welcome, Alex</h1>
      <h4 className="text-2xl text-lightAlt mb-5">Your tasks</h4>
      {/* Todos */}
      <div className="">
        {todos.map((todo) => (
          <Todo
            key={todo._id}
            text={todo.text}
            complete={todo.complete}
            onClick={() => completeToDo(todo._id)}
            deleteTodo={() => deleteTodo(todo._id)}
          />
        ))}
      </div>
    </div>
  );
}
