GET http://localhost:3002/todos

###

POST http://localhost:3002/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}

###

DELETE http://localhost:3002/todo/delete/6400cfe04c84d6e118898c63

###

PUT http://localhost:3002/todo/complete/6405f687ae86c3fb9d985007